<Project>
  <PropertyGroup>
    <StoreIdentityName Condition="'$(StoreIdentityName)' == ''">KynoraStudio.Noctra</StoreIdentityName>
    <StorePublisher Condition="'$(StorePublisher)' == ''">CN=04656601-52D3-46A0-9923-865AED08FC7B</StorePublisher>
    <StorePublisherDisplayName Condition="'$(StorePublisherDisplayName)' == ''">Kynora Studio</StorePublisherDisplayName>
  </PropertyGroup>
</Project>
